name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        mode: [ Debug, Release ]

    env:
      CXX: cl.exe
      CC: cl.exe
      BUILDCACHE_COMPRESS: true
      BUILDCACHE_DIRECT_MODE: true
      BUILDCACHE_DIR: ${{ github.workspace }}/.buildcache
      BUILDCACHE_ACCURACY: SLOPPY
      BUILDCACHE_LUA_PATH: ${{ github.workspace }}/tools
      CLICOLOR_FORCE: 1

    steps:
      - uses: actions/checkout@v3

      - name: Install ninja
        run: choco install ninja

      # ==== RESTORE CACHE ====
      - name: Restore buildcache Cache
        uses: actions/cache/restore@v3
        id: restore-buildcache
        with:
          path: ${{ github.workspace }}/.buildcache
          key: buildcache-windows-${{ matrix.mode }}-${{ hashFiles('.pkg') }}-${{ hashFiles('**/*.h') }}-${{ hashFiles('**/*.cc') }}
          restore-keys: |
            buildcache-windows-${{ matrix.mode }}-${{ hashFiles('.pkg') }}-${{ hashFiles('**/*.h') }}
            buildcache-windows-${{ matrix.mode }}-${{ hashFiles('.pkg') }}-
            buildcache-windows-${{ matrix.mode }}-

      - name: Restore Dependencies Cache
        uses: actions/cache/restore@v3
        id: restore-deps-cache
        with:
          path: ${{ github.workspace }}/deps
          key: deps-${{ hashFiles('.pkg') }}
          restore-keys: deps-

      # ==== BUILD ====
      - name: Build
        run: |
          $devShell = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -find **\Microsoft.VisualStudio.DevShell.dll
          $installPath = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationpath
          Import-Module $devShell
          Enter-VsDevShell -VsInstallPath $installPath -SkipAutomaticLocation -DevCmdArguments "-arch=amd64"
          Get-ChildItem env:
          cmake -GNinja -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DTRANSFERS_DEBUG_SYMBOLS=OFF -DTRANSFERS_MIMALLOC=ON
          .\build\buildcache\bin\buildcache.exe -z
          cmake --build build --target transfers
          $CompilerExitCode = $LastExitCode
          Copy-Item ${env:VCToolsRedistDir}x64\Microsoft.VC143.CRT\*.dll .\build\
          .\build\buildcache\bin\buildcache.exe -s
          exit $CompilerExitCode

      # ==== SAVE CACHE ====
      - name: Save buildcache Cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/.buildcache
          key: ${{ steps.restore-buildcache.outputs.cache-primary-key }}

      - name: Save Dependencies Cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/deps
          key: ${{ steps.restore-deps-cache.outputs.cache-primary-key }}
